[workspace] # プロジェクト全体を管理するCargoワークスペースの宣言
members = [ # このワークスペースに含めるクレート一覧
    "core",  # 定数や構造体を集約したコアライブラリクレート
    "dfuji", # 既存の天文計算ロジックをまとめたライブラリクレート
    "cli",   # clapベースでdfujiライブラリを呼び出す新規CLIクレート
]
resolver = "2" # 依存解決アルゴリズムとしてRust推奨の第2世代リゾルバを使用

[workspace.metadata]
rust-analyzer = { linkedProjects = ["dfuji/Cargo.toml", "cli/Cargo.toml"] }
