[package]
name = "dfuji-geo"
description = "WGS84 楕円体に基づく地理座標計算ライブラリ（方位角・高度角・距離）"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dfuji-core = { path = "../core" }
geographiclib-rs = "^0.2.7"
geojson = "0.24.2"
